import { Button, Pane, Text, majorScale } from "evergreen-ui";
import Head from "next/head";
import styles from "@/styles/First.module.css";

export default function First() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Pane display="flex" alignItems="center" marginX={majorScale(2)}>
          <Button>Click me!</Button>
          <Text>This is a clickable Button</Text>
        </Pane>

        <Pane display="flex" alignItems="center" marginX={majorScale(2)}>
          <Button>Click me!</Button>
          <Text>This is a clickable Button</Text>
        </Pane>

        <Pane clearfix>
          <Pane
            elevation={0}
            float="left"
            backgroundColor="white"
            width={200}
            height={120}
            margin={24}
            display="flex"
            justifyContent="center"
            alignItems="center"
            flexDirection="column"
          >
            <Text>Elevation 0</Text>
            <Text size={300}>Flat Panes</Text>
          </Pane>
          <Pane
            elevation={1}
            float="left"
            width={200}
            height={120}
            margin={24}
            display="flex"
            justifyContent="center"
            alignItems="center"
            flexDirection="column"
          >
            <Text>Elevation 1</Text>
            <Text size={300}>Floating Panes</Text>
          </Pane>
          <Pane
            elevation={2}
            float="left"
            width={200}
            height={120}
            margin={24}
            display="flex"
            justifyContent="center"
            alignItems="center"
            flexDirection="column"
          >
            <Text>Elevation 2</Text>
            <Text size={300}>Popovers and Dropdowns</Text>
          </Pane>
          <Pane
            elevation={3}
            float="left"
            width={200}
            height={120}
            margin={24}
            display="flex"
            justifyContent="center"
            alignItems="center"
            flexDirection="column"
          >
            <Text>Elevation 3</Text>
            <Text size={300}>Toasts</Text>
          </Pane>
          <Pane
            elevation={4}
            float="left"
            width={200}
            height={120}
            margin={24}
            display="flex"
            justifyContent="center"
            alignItems="center"
            flexDirection="column"
          >
            <Text>Elevation 4</Text>
            <Text size={300}>Dialog</Text>
          </Pane>
        </Pane>
      </main>
    </>
  );
}
