import { Button, Pane, Text, majorScale } from "evergreen-ui";
import Head from "next/head";
import styles from "@/styles/Second.module.css";

export default function Second() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Pane className={styles.width}>
          <Pane className={styles.horizontal}>
            <Pane className={styles.halves}>
              <Pane display="flex" alignItems="center" marginX={majorScale(2)}>
                <Button>Click me!</Button>
                <Text>This is a clickable Button</Text>
              </Pane>

              <Pane display="flex" alignItems="center" marginX={majorScale(2)}>
                <Button>Click me!</Button>
                <Text>This is a clickable Button</Text>
              </Pane>
            </Pane>

            <Pane className={styles.halves}>
              <Pane display="flex" alignItems="center" marginX={majorScale(2)}>
                <Button>Click me!</Button>
                <Text>This is a clickable Button</Text>
              </Pane>

              <Pane display="flex" alignItems="center" marginX={majorScale(2)}>
                <Button>Click me!</Button>
                <Text>This is a clickable Button</Text>
              </Pane>
            </Pane>
          </Pane>
        </Pane>
      </main>
    </>
  );
}
