import {
  Button,
  Pane,
  Text,
  majorScale,
  Card,
  IconButton,
  CogIcon,
  TrashIcon,
  TickIcon,
  EditIcon,
  ManualIcon,
  SearchIcon,
  CaretDownIcon,
  Table,
  PredictiveAnalysisIcon,
} from "evergreen-ui";
import Head from "next/head";
import styles from "@/styles/Second.module.css";
import { LightWeightChart } from "@/components/LightWeightChart";
import { GetServerSideProps, InferGetServerSidePropsType } from "next/types";
import { fetchTopMedium, TDCandles } from "./api/medium";

export const getServerSideProps: GetServerSideProps<{
  isConnected: boolean;
  medium?: TDCandles;
}> = async ({ req, res }) => {
  try {
    res.setHeader(
      "Cache-Control",
      "public, s-maxage=60, stale-while-revalidate=59"
    );

    const mediumResponse = await fetchTopMedium();
    if (!mediumResponse) {
      throw "error in fetchTopMedium";
    }
    return {
      props: {
        isConnected: true,
        medium: mediumResponse.medium[1],
      },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }
};

export default function SignleChart({
  medium,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Pane className={styles.horizontal}>
          <Pane className={styles.gridcontainer}>
            <Card
              border="0.125rem solid"
              borderColor="black"
              background="tint1"
              padding={majorScale(2)}
              className={styles.max}
            >
              <Pane display="flex" alignItems="center">
                <Pane width={"100%"} className={styles.gridcontainer}>
                  <Pane
                    display="flex"
                    justifyContent="space-between"
                    alignItems="center"
                  >
                    <Pane>TSLA</Pane>
                    <Pane>+$556</Pane>
                  </Pane>
                  <Pane
                    display="flex"
                    justifyContent="space-between"
                    alignItems="center"
                  >
                    <Pane># 6sigma, easy, wide</Pane>
                    <Pane>Score: 656</Pane>
                  </Pane>
                </Pane>
              </Pane>
            </Card>
            <Card
              border="0.125rem solid"
              borderColor="black"
              background="tint1"
              padding={majorScale(1)}
              marginX="auto"
              alignItems="center"
            >
              {medium && (
                <LightWeightChart
                  candlesData={medium.candles}
                ></LightWeightChart>
              )}
            </Card>
            <Pane>
              <Pane display="flex" alignItems="center" marginX={majorScale(2)}>
                <IconButton icon={CogIcon} marginRight={majorScale(2)} />
                <IconButton
                  icon={TrashIcon}
                  intent="danger"
                  marginRight={majorScale(2)}
                />
                <IconButton icon={TickIcon} intent="success" />
              </Pane>
            </Pane>
          </Pane>
        </Pane>
      </main>
    </>
  );
}
