import { Button, Pane, Text, majorScale, Table } from "evergreen-ui";
import Head from "next/head";
import styles from "@/styles/First.module.css";

const profiles = [
  "RSI",
  "VOLUME",
  "MACD",
  "BANDS",
  "STDDEV",
  "POLYFIT",
  "MINMAX",
  "FLAT",
];

export default function TableOne() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Table.Head>
          <Table.SearchHeaderCell
            onChange={(value) => console.log(value)}
            placeholder="Search by email..."
          />
          <Table.TextHeaderCell>Last Activity</Table.TextHeaderCell>
          <Table.TextHeaderCell>ltv</Table.TextHeaderCell>
        </Table.Head>
        <Table.Body height={240}>
          {groupIntoN(profiles, 3).map((chunk) => (
            <Table.Row
              isSelectable
              // onSelect={() => alert(chunk)}
              key={chunk[0]}
            >
              {chunk.map((profile) => (
                <Table.TextCell
                  isSelectable
                  onSelect={() => alert(profile)}
                  key={profile}
                >
                  {profile}
                </Table.TextCell>
              ))}
            </Table.Row>
          ))}
        </Table.Body>
      </main>
    </>
  );
}

/**
 * Example: groupIntoN([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 3) => [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10]]
 * @param array
 * @param n
 * @returns
 */
function groupIntoN<T>(array: T[], n: number) {
  const result = [];

  for (let i = 0; i < array.length; i += 5) {
    result.push(array.slice(i, i + n));
  }

  return result;
}
